config/routes.rb
Rails.application.routes.draw do
  root to: 'divisions#index'
  resources :divisions do
    resources :employees
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees, dependent: :destroy

  validates :name, presence: true
  validates_length_of :name, maximum: 100

  before_save(:titleize_division)

  private
  def titleize_division
    self.name = self.name.titleize
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division

  validates :name, presence: true
  validates_length_of :name, maximum: 100

  before_save(:titleize_employee)

  private
  def titleize_employee
    self.name = self.name.titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index
    @divisions = Division.all
    render :index
  end

  def new
    @division = Division.new
    render :new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      redirect_to divisions_path
    else
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
    render :edit
  end

  def show
    @division = Division.find(params[:id])
    render :show
  end

  def update
    @division = Division.find(params[:id])
    if @division.update(division_params)
      redirect_to divisions_path
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end

  private
    def division_params
      params.require(:division).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all
    render :index
  end

  def new
    @division = Division.find(params[:division_id])
    @employee  = Employee.new
    render :new
  end

  def create
    @division = Division.find(params[:division_id])
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to divison_path(@division)
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    render :edit
  end

  def show
    @employee = Employee.find(params[:id])
    render :show
  end

  def update
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to divison_path(@division)
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to divison_path(@division)
  end

  private
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h3>Edit <%= @division.name %></h3>

<%= render "layouts/division_form" %>

app/views/divisions/index.html.erb
<h1>Divisions</h1>

<% if @divisions.any? %>
  <% @divisions.each do |division| %>
    <p><%= link_to division.name, division_path(division) %></p>
  <% end %>
<% else %>
  <p>There are no divisions yet.</p>
<% end %>


<p><%= link_to "Create Division", new_division_path %></p>

app/views/divisions/new.html.erb
<h3>New Division</h3>

<%= render template: "layouts/division_form" %>

app/views/divisions/show.html.erb
<h1><%= @division.name %></h1>

<% if @division.employees.any? %>
  <h4>Here are the employees for this division:</h4>

  <% @division.employees.each do |employee| %>
    <ul>
      <li>
        <%= link_to employee.name, division_employee_path(@division, employee) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed for this division.</p>
<% end %>

<p><%= link_to "Add a employee", new_division_employee_path(@division) %></p>

<p><%= link_to "Edit", edit_division_path(@division) %></p>
<p><%= link_to "Delete", division_path(@division),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Divisions", divisions_path %></p>

app/views/layouts/_division_form.html.erb
<%= render "layouts/errors", :object => @division %>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>